idf_component_register(
    SRCS
        "flora-sense.c"
        "wifi.c"
        "ble_client.c"
        "ble_server.c"
        "http_client.c"
        "motor_controller.c"
        "sensors/sensor_light.c"
        "sensors/sensor_proximity.c"
        "sensors/sensor_soil.c"
        "sensors/sensor_temp.c"
        "sensors/sensor_hall.c"
        "sensors/sensor_dock.c"
        "sensors/sensor_ir.c"
        "sensors/hardware_test.c"
        "mqtt_client.c"
        "bmp280.c"
        "bmp280.h"
        "mpu6050_test.c"
        "mpu6050_test.h"
        "mpu6050.c"
        "mpu6050.h"
    INCLUDE_DIRS
        "." "sensors"
    REQUIRES
        bt
        nvs_flash
        esp_http_client
        esp_netif
        freertos
        driver
        esp_driver_gpio
        esp_driver_i2c
        esp_wifi
        lwip
        mqtt
)
