idf_component_register(
    SRCS
        "flora-sense.c"
        "wifi.c"
        "certs.c"
        "ble_dock_client.c"
        "motor_controller.c"
        "sensors/sensor_light.c"
        "sensors/adc_shared.c"
        "sensors/sensor_soil.c"
        "sensors/sensor_temp.c"
        "sensors/sensor_hall.c"
        "sensors/sensor_dock.c"
        "sensors/sensor_ir.c"
        "sensors/sensor_battery.c"
        "mqtt_client.c"
        "wsn_controller.c"
        "water_controller.c"
    INCLUDE_DIRS
        "." "sensors"
    REQUIRES
        bt
        nvs_flash
        esp_netif
        freertos
        driver
        esp_driver_gpio
        esp_driver_i2c
        esp_http_server 
        esp_https_server
        mbedtls
        esp_wifi
        lwip
        esp_adc
        mqtt
        esp_driver_ledc
        cjson
)
